name: Add labels to issue

on:
  workflow_call:
    inputs:
      issue-number:
        required: true
        type: string
      issue-url:
        required: true
        type: string
      labels:
        required: true
        type: string
    secrets: inherit

jobs:
  add-labels:
    name: Add labels to issue
    runs-on: ubuntu-latest
    steps:
      - name: Add given labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.github-pat }}
          script: |
            try {
              const response = await github.rest.issues.addLabels({
                repo: context.repo.repo,
                owner: context.repo.owner,
                issue_number: ${{ inputs.issue-number }},
                labels: [${{ inputs.labels }}]
              });
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Exporting result
        run: echo '## Added label(s) ${{ inputs.label }} on [${{ inputs.issue-number }}](${{ inputs.issue-url }})' >> $GITHUB_STEP_SUMMARY
